variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd Guardians

    - ./gradlew assemble

test:
  stage: test
  script:
    - cd Guardians

    - ./gradlew test

sonar:
  stage: .post
  script:
    - cd Guardians
    - ./gradlew sonar
    - ./gradlew --stop