variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test

build:
  stage: build
  script:
    - pets-guardian-fork-copy/Guardians

    - ./gradlew assemble

test:
  stage: test
  script:
    - cd pets-guardian-fork-copy/Guardians

    - ./gradlew test

sonar:
  stage: .post
  script:
    - ./gradlew sonar
    - ./gradlew --stop