variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_DEPTH: "1000"

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd Guardians

    - ./gradlew assemble

test:
  stage: test
  script:
    - cd Guardians

    - ./gradlew test
    -  ./gradlew --stop

sonar:
  stage: .post
  script:
    - cd Guardians
    - ./gradlew sonar
    - ./gradlew --stop

#deploy:
#  stage: deploy
#  script:
#    - cd Guardians
#    - ./gradlew bootJar
#    - java -jar build/libs/guardians-0.0.1-SNAPSHOT.jar
#
#
#production:
#  stage: .post
#  script:
#    - cd Guardians
#    - ./gradlew build -Penv=production
